---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-settings
  namespace: logging
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/elk
    server: 192.168.56.200
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-settings
  namespace: logging
spec:
  volumeMode: Filesystem
  volumeName: elk-settings
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
