- name: JAVA
  hosts: "{{ variable_host }}"
  remote_user: root
  tasks:
    - name: JAVA - Installing
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

- name: Jenkins
  hosts: "{{ variable_host }}"
  remote_user: root
  tasks:
    - name: Jenkins - Add repository key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present
      when: ansible_facts['hostname'] == "jenkins-master"
    
    - name: Jenkins - Add repository
      ansible.builtin.apt_repository:
        repo: "deb https://pkg.jenkins.io/debian binary/"
        state: present
      when: ansible_facts['hostname'] == "jenkins-master"

    - name: Jenkins - Installing
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: yes
      when: ansible_facts['hostname'] == "jenkins-master"

- name: Docker
  hosts: "{{ variable_host }}"
  remote_user: root
  tasks:
    - name: Docker - Prerequisite
      apt: 
        name: ca-certificates, curl, gnupg, lsb-release
        state: latest
        update_cache: yes

    - name: Docker - Add repository key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Docker - Add repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Docker - Installing
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Docker - Add jenkins user to Docker's group
      ansible.builtin.user:
        name: jenkins
        groups: docker
        state: present
        append: yes

    - name: Docker - Set permissions
      ansible.builtin.file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0666'

    - name: Jenkins - Restart
      ansible.builtin.service:
        name: jenkins
        state: restarted
      when: ansible_facts['hostname'] == "jenkins-master"

    - name: Jenkins - Git Safe Directory
      ansible.builtin.command: git config --global --add safe.directory /home/vagrant/agent/workspace/oracle

- name: kubectl
  hosts: "{{ variable_host }}"
  tasks:
    - name: kubectl - Prerequisite
      ansible.builtin.apt:
        name: ca-certificates, curl
        state: present

    - name: kubectl - Add repository key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: kubectl - Add repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: "kubernetes"

    - name: kubectl - Installing
      ansible.builtin.apt:
        name: kubectl
        state: present

- name: Unlock Jenkins
  hosts: "{{ variable_host }}"
  tasks:
    - name: Jenkins - Register Unlock key
      ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: key
      when: ansible_facts['hostname'] == "jenkins-master"

    - name: Jenkins - Show Unlock key
      ansible.builtin.debug:
        msg: "{{ key.stdout }}"
      when: ansible_facts['hostname'] == "jenkins-master"