Vagrant.configure('2') do |config|

  config.env.enable
  config.vm.boot_timeout = 1200

  config.vm.define 'puppet' do |puppet|

      puppet.vm.box = 'ubuntu/focal64'
      puppet.vm.hostname = 'puppet.localdomain'
      puppet.vm.network 'private_network', ip: ENV['PUPPET_IP']

      puppet.vm.provision 'shell', inline: 'echo "$IP agent agent.localdomain" >> /etc/hosts', env: {"IP" => ENV['AGENT_IP']}
      puppet.vm.provision 'shell', inline: 'sudo apt install -y git wget'
      puppet.vm.provision 'shell', inline: 'wget https://apt.puppetlabs.com/puppet7-release-focal.deb'
      puppet.vm.provision 'shell', inline: 'sudo dpkg -i puppet7-release-focal.deb'
      puppet.vm.provision 'shell', inline: 'sudo apt update -y'
      puppet.vm.provision 'shell', inline: 'echo "export PATH=$PATH:/opt/puppetlabs/puppet/bin" >> /root/.bashrc'
      puppet.vm.provision 'shell', inline: 'sudo apt install -y puppetserver'
      puppet.vm.provision 'shell', inline: 'systemctl enable puppetserver --now'

      puppet.vm.provider 'virtualbox' do |vb|
          vb.memory = 4096
          vb.cpus = 4
          vb.name = 'puppet.localdomain'

      end

  end

  config.vm.define 'agent' do |agent|

      agent.vm.box = 'ubuntu/focal64'
      agent.vm.hostname = 'agent.localdomain'
      agent.vm.network 'private_network', ip: ENV['AGENT_IP']

      agent.vm.provision 'shell', inline: 'echo "$IP puppet puppet.localdomain" >> /etc/hosts', env: {"IP" => ENV['PUPPET_IP']}
      agent.vm.provision 'shell', inline: 'sudo apt install -y git wget'
      agent.vm.provision 'shell', inline: 'wget https://apt.puppetlabs.com/puppet7-release-focal.deb'
      agent.vm.provision 'shell', inline: 'sudo dpkg -i puppet7-release-focal.deb'
      agent.vm.provision 'shell', inline: 'sudo apt update -y'
      agent.vm.provision 'shell', inline: 'echo "export PATH=$PATH:/opt/puppetlabs/puppet/bin" >> /root/.bashrc'
      agent.vm.provision 'shell', inline: 'sudo apt install -y puppet-agent'
      agent.vm.provision 'shell', inline: 'sudo puppet config set server puppet.localdomain --section main'

      agent.vm.provider 'virtualbox' do |vb|
          vb.memory = 2048
          vb.cpus = 4
          vb.name = 'agent.localdomain'

      end

  end

end