---

- name: Nginx - Deploy and Check Status
  hosts: all
  tasks:
        - name: Install epel-release
          yum:
            name: epel-release
            state: latest

        - name: Install Nginx Web Server
          yum:
            name: nginx
            state: latest

        - name: Start service Nginx
          ansible.builtin.service:
            name: nginx
            state: started
            enabled: yes

...
