version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - /home/vagrant/volumes/elk/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /home/vagrant/volumes/elk/elastic/snap:/snap
      - /home/vagrant/volumes/elk/elastic/data:/data
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: basic
      xpack.monitoring.collection.enabled: true
      xpack.security.enabled: false
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      STACK_VERSION: ${STACK_VERSION}
      ELASTIC_PORT: ${ELASTIC_PORT}
      KIBANA_PORT: ${KIBANA_PORT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    restart: unless-stopped
    environment:
      SERVER_NAME: kibana
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOSTS: ${ELASTIC_HOST}
      KIBANA_USERNAME: ${KIBANA_USERNAME}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
    ports:
      - '5601:5601'
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks:
  elk-network:
    driver: bridge