---

- name: Update/Upgrade Systems - Starting Deploy
  hosts: all
  tasks:
        - name: CentOS | Update System
          yum: name=* state=latest update_cache=yes
          when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

        - name: Oracle Linux Server | Update System
          yum: name=* state=latest update_cache=yes
          when: ansible_distribution == "OracleLinux"

        - name: Debian | Update System
          apt: update_cache=yes
          when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

...
