AWX:
  # enable use of awx-deploy template
  enabled: true
  name: awx
  spec:
    admin_user: admin

  # configurations for external postgres instance
  postgres:
    enabled: false
    host: awx-postgres-13
    port: 5432
    dbName: awx_db
    username: awx
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    type: managed
