apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: awx-storageclass
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-storage
  namespace: awx
spec:
  volumeMode: Filesystem
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/awx
    server: 192.168.56.200
  storageClassName: "awx-storageclass"

