Vagrant.configure('2') do |config|

    config.env.enable
    config.vm.boot_timeout = 1200

    config.vm.define 'grafana_srv' do |grafana_srv|

        grafana_srv.vm.box = 'ubuntu/focal64'
        grafana_srv.vm.hostname = 'grafana-srv'
        grafana_srv.vm.network 'public_network', ip: ENV['GRAFANA_IP'], bridge: ENV['INTERFACE_LAN']

        grafana_srv.vm.provision 'shell', inline: 'sudo timedatectl set-timezone America/Sao_Paulo'
        grafana_srv.vm.provision 'shell', inline: 'sudo cp /vagrant/files/ntpdate.sh /etc/cron.hourly/'
        grafana_srv.vm.provision 'shell', inline: 'sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
        grafana_srv.vm.provision 'shell', inline: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
        grafana_srv.vm.provision 'shell', inline: 'sudo apt-get update'
        grafana_srv.vm.provision 'shell', inline: 'sudo apt-get install -y docker-ce ca-certificates curl openssh-server python ntpdate acl'
        grafana_srv.vm.provision 'shell', inline: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
        grafana_srv.vm.provision 'shell', inline: 'sudo chmod +x /usr/local/bin/docker-compose'
        grafana_srv.vm.provision 'shell', inline: 'sudo setfacl -m user:vagrant:rw /var/run/docker.sock'
        grafana_srv.vm.provision 'shell', inline: 'sudo usermod -aG docker vagrant'
        grafana_srv.vm.provision 'shell', inline: 'mkdir -p /home/vagrant/volumes/grafana'
        grafana_srv.vm.provision 'shell', inline: 'mkdir -p /home/vagrant/volumes/influxdb'
        grafana_srv.vm.provision 'shell', inline: 'sudo chown vagrant. -R /home/vagrant/volumes'
        grafana_srv.vm.provision 'shell', inline: 'docker network create grafana-net'
        grafana_srv.vm.provision 'shell', inline: 'docker run -d --user 1000 -v /home/vagrant/volumes/grafana/:/var/lib/grafana -p 3000:3000 --restart always --name=grafana --network=grafana-net grafana/grafana'
        grafana_srv.vm.provision 'shell', inline: 'docker run -d -v /home/vagrant/volumes/influxdb/:/var/lib/influxdb -p 8083:8083 -p 8086:8086 -p 25826:25826/udp --restart always --name=influxdb --network=grafana-net influxdb:2.1.1'

        grafana_srv.vm.provider 'virtualbox' do |vb|
            vb.memory = 4096
            vb.cpus = 4
            vb.name = 'grafana-srv'
            vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']

        end

    end

    config.vm.define 'centos_srv03' do |centos_srv03|

        centos_srv03.vm.box = 'centos/7'
        centos_srv03.vm.hostname = 'centos-srv03'
        centos_srv03.vm.network 'public_network', ip: ENV['CENTOS_SRV03'], bridge: ENV['INTERFACE_LAN']

        centos_srv03.vm.provision 'shell', inline: 'sudo timedatectl set-timezone America/Sao_Paulo'
        centos_srv03.vm.provision 'shell', inline: 'sudo cp /vagrant/files/ntpdate.sh /etc/cron.hourly/'
        centos_srv03.vm.provision 'shell', inline: 'sudo cp /vagrant/files/influxdb.repo /etc/yum.repos.d/'
        centos_srv03.vm.provision 'shell', inline: 'sudo sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config && sudo setenforce 0'
        centos_srv03.vm.provision 'shell', inline: 'sudo systemctl stop firewalld && sudo systemctl disable firewalld'
        centos_srv03.vm.provision 'shell', inline: 'sudo curl -fsSL https://get.docker.com/ | sh'
        centos_srv03.vm.provision 'shell', inline: 'sudo systemctl start docker && sudo systemctl enable docker'
        centos_srv03.vm.provision 'shell', inline: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
        centos_srv03.vm.provision 'shell', inline: 'sudo chmod +x /usr/local/bin/docker-compose'
        centos_srv03.vm.provision 'shell', inline: 'sudo setfacl -m user:vagrant:rw /var/run/docker.sock'
        centos_srv03.vm.provision 'shell', inline: 'sudo setfacl -m user:telegraf:rw /var/run/docker.sock'
        centos_srv03.vm.provision 'shell', inline: 'sudo yum install -y epel-release'
        centos_srv03.vm.provision 'shell', inline: 'sudo yum install -y git ntpdate telegraf htop stress-ng httpd vim'
        centos_srv03.vm.provision 'shell', inline: 'sudo mv /etc/telegraf/telegraf.conf /etc/telegraf/telegraf.conf.bkp'
        centos_srv03.vm.provision 'shell', inline: 'sudo cp /vagrant/files/telegraf.conf /etc/telegraf/telegraf.conf'
        centos_srv03.vm.provision 'shell', inline: 'sudo usermod -aG docker telegraf'
        centos_srv03.vm.provision 'shell', inline: 'sudo usermod -aG docker vagrant'
        centos_srv03.vm.provision 'shell', inline: 'sudo usermod -aG adm telegraf'
        centos_srv03.vm.provision 'shell', inline: 'sudo systemctl start telegraf && sudo systemctl enable telegraf'
        centos_srv03.vm.provision 'shell', inline: 'sudo systemctl start httpd && sudo systemctl enable httpd'
        centos_srv03.vm.provision 'shell', inline: 'sudo docker run -it -d -p 8080:80 --restart always --name web nginx'

        centos_srv03.vm.provider 'virtualbox' do |vb|
            vb.memory = 1024
            vb.cpus = 1
            vb.name = 'centos-srv03'
            vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']

        end

    end

end