---

- name: INCLUDE VARS
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - vars/vars_install_webserver.yml

- name: UBUNTU INSTALL MARIADB
  block:

    - name: UBUNTU | Apt Update
      ansible.builtin.shell: "apt update"

    - name: UBUNTU | Install package {{ ubuntu_package }}
      ansible.builtin.apt:
        name: "{{ ubuntu_package }}"
        state: latest

    - name: UBUNTU | Check version installed
      ansible.builtin.shell: "apt list --installed | grep nginx"
      register: ubuntu_packageversion

    - name: UBUNTU | Show nginx Version
      debug:
        msg: "nginx Version is {{ ubuntu_packageversion.stdout }}"

  when:
    - ansible_facts['distribution'] is defined and ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_major_version'] == '20'

- name: RHEL INSTALL PACKAGE
  block:

    - name: RHEL | Install package {{ rhel_package }}
      ansible.builtin.yum:
        name: "{{ rhel_package }}"
        state: latest

    - name: RHEL | Check version installed
      ansible.builtin.shell: "rpm -qa nginx"
      register: rhel_packageversion

    - name: RHEL | Show nginx Version
      debug:
        msg: "nginx Version is {{ rhel_packageversion.stdout }}"

  when:
    - ansible_facts['distribution'] is defined and ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '7.8'

...